// This is a fallback list of words for the game.
// The primary source should be Firestore.
export const WORDLIST = [
  'aback', 'abase', 'abate', 'abbey', 'abbot', 'abhor', 'abide', 'abled', 
  'abode', 'abort', 'about', 'above', 'abuse', 'abyss', 'acorn', 'acrid', 
  'actor', 'acute', 'adage', 'adapt', 'adept', 'admin', 'admit', 'adobe', 
  'adopt', 'adore', 'adorn', 'adult', 'affix', 'afire', 'afoot', 'afoul', 
  'after', 'again', 'agape', 'agate', 'agent', 'agile', 'aging', 'aglow', 
  'agony', 'agree', 'ahead', 'aider', 'aisle', 'alarm', 'album', 'alert', 
  'algae', 'alibi', 'alien', 'align', 'alike', 'alive', 'allay', 'alley', 
  'allot', 'allow', 'alloy', 'aloft', 'alone', 'along', 'aloof', 'aloud', 
  'alpha', 'altar', 'alter', 'amass', 'amaze', 'amber', 'amble', 'amend', 
  'amiss', 'amity', 'among', 'ample', 'amply', 'amuse', 'angel', 'anger', 
  'angle', 'angry', 'angst', 'anime', 'ankle', 'annex', 'annoy', 'annul', 
  'anode', 'antic', 'anvil', 'aorta', 'apart', 'aphid', 'aping', 'apnea', 
  'apple', 'apply', 'apron', 'aptly', 'arbor', 'ardor', 'arena', 'argon', 
  'argue', 'arise', 'armor', 'aroma', 'arose', 'array', 'arrow', 'arson', 
  'artsy', 'ascot', 'ashen', 'aside', 'askew', 'assay', 'asset', 'atoll', 
  'atone', 'attic', 'audio', 'audit', 'augur', 'aunty', 'avail', 'avert', 
  'avian', 'avoid', 'await', 'awake', 'award', 'aware', 'awash', 'awful', 
  'awoke', 'axial', 'axiom', 'axion', 'azure'
];

// A larger set of valid 5-letter guesses.
// In a real application, this might also be stored in a database or a service.
export const VALID_GUESSES = new Set([
  ...WORDLIST,
  'aahed', 'aalii', 'aargh', 'aarti', 'abaca', 'abaci', 'abacs', 'abaft', 
  'abaka', 'abamp', 'aband', 'abash', 'abask', 'abaya', 'abbas', 'abbed', 
  'abbes', 'abcee', 'abeam', 'abear', 'abele', 'abers', 'abets', 'abies', 
  'abohm', 'aboil', 'aboma', 'aboon', 'abord', 'abore', 'abram', 'abray', 
  'abrim', 'abrin', 'abris', 'absey', 'absit', 'abuna', 'abune', 'abuts', 
  'abuzz', 'abyes', 'abysm', 'acais', 'acari', 'accas', 'accoy', 'acerb', 
  'acers', 'aceta', 'achar', 'ached', 'aches', 'achoo', 'acids', 'acidy', 
  'acing', 'acini', 'ackee', 'acker', 'acmes', 'acmic', 'acned', 'acnes', 
  'acock', 'acold', 'acred', 'acres', 'acros', 'acted', 'actin', 'acton', 
  'acyls', 'adaws', 'adays', 'adbot', 'addax', 'added', 'adder', 'addio', 
  'addle', 'adeem', 'adhan', 'adieu', 'adios', 'adits', 'adman', 'admen', 
  'admix', 'adobo', 'adown', 'adoze', 'adrad', 'adred', 'adsum', 'aduki', 
  'adunc', 'adust', 'advew', 'adyta', 'adzed', 'adzes', 'aecia', 'aedes', 
  'aegis', 'aeons', 'aerie', 'aeros', 'aesir', 'afald', 'afear', 'affly', 
  'afion', 'afore', 'afret', 'afrit', 'afros', 'agama', 'agami', 'agars', 
  'agast', 'agave', 'agaze', 'agene', 'agers', 'agger', 'aggie', 'aggri', 
  'aggro', 'aggry', 'aghas', 'agila', 'agios', 'agism', 'agist', 'agita', 
  'aglee', 'aglet', 'agley', 'agloo', 'aglus', 'agmas', 'agoge', 'agone', 
  'agons', 'agood', 'agora', 'agria', 'agrin', 'agros', 'agued', 'agues', 
  'aguti', 'aheap', 'ahent', 'ahigh', 'ahind', 'ahing', 'ahint', 'ahold', 
  'ahull', 'ahuru', 'aidas', 'aided', 'aides', 'aidoi', 'aidos', 'aiery', 
  'aigas', 'aighs', 'ailed', 'aimed', 'aimer', 'ainee', 'ainga', 'aioli', 
  'aired', 'airer', 'airns', 'airth', 'airts', 'aitch', 'aitus', 'aiver', 
  'aiyee', 'aizle', 'ajies', 'ajiva', 'ajuga', 'ajwan', 'akees', 'akela', 
  'akene', 'aking', 'akita', 'akkas', 'alaap', 'alack', 'alamo', 'aland', 
  'alane', 'alang', 'alans', 'alant', 'alapa', 'alaps', 'alary', 'alate', 
  'alays', 'albas', 'albee', 'alcid', 'alcos', 'aldea', 'alder', 'aldol', 
  'aleck', 'alecs', 'alefs', 'aleft', 'aleph', 'alews', 'aleye', 'alfas', 
  'algal', 'algas', 'algid', 'algin', 'algor', 'algum', 'alias', 'alifs', 
  'aline', 'alist', 'aliya', 'alkie', 'alkos', 'alkyd', 'alkyl', 'allee', 
  'allel', 'allis', 'allod', 'allyl', 'almah', 'almas', 'almeh', 'almes', 
  'almud', 'almug', 'alods', 'aloed', 'aloes', 'login', 'loipe', 'loirs',
  'lokes', 'lolls', 'lolly', 'lolog', 'lolos', 'lomas', 'lomen', 'lomes',
  'loner', 'longa', 'longe', 'longs', 'looby', 'looed', 'looey', 'loofa',
  'loofs', 'looie', 'looks', 'looky', 'looms', 'loons', 'loony', 'loops',
  'loopy', 'loord', 'loose', 'loots', 'loped', 'loper', 'lopes', 'loppy',
  'loral', 'loran', 'lords', 'lordy', 'lorel', 'lores', 'loric', 'loris',
  'losed', 'losel', 'losen', 'loser', 'loses', 'lossy', 'lotah', 'lotas',
  'lotes', 'lotic', 'lotos', 'lotsa', 'lotta', 'lotte', 'lotto', 'lotus',
  'loued', 'lough', 'louie', 'louis', 'louma', 'lound', 'louns', 'loupe',
  'loups', 'loure', 'lours', 'loury', 'louse', 'lousy', 'louts', 'lovat',
  'loved', 'lovee', 'lover', 'loves', 'lovey', 'lovie', 'lowan', 'lowed',
  'lowen', 'lower', 'lowes', 'lownd', 'lowne', 'lowns', 'lowps', 'lowry',
  'lowse', 'lowts', 'loxed', 'loxes', 'lozen', 'luach', 'luaus', 'lubed',
  'lubes', 'lubra', 'luces', 'lucks', 'lucky', 'lucre', 'ludes', 'ludic',
  'zydeco', 'zygal', 'zygon', 'zymes', 'zymic'
]);
